import { i18n } from "../ThandulsTogglableEffects";

export let LANG_EFFECT:any = {};

export const initLangEffect = function(){

  LANG_EFFECT.ButtonsSceneName = i18n("ThandulsTogglableEffects.ButtonsSceneName"),
  LANG_EFFECT.ButtonsSceneTitle = i18n("ThandulsTogglableEffects.ButtonsSceneTitle"),
  LANG_EFFECT.ButtonsSceneTitleDialog = i18n("ThandulsTogglableEffects.ButtonsSceneTitleDialog"),

  LANG_EFFECT.settingsShowForPlayersName = i18n("ThandulsTogglableEffects.settingsShowForPlayers-name"),
  LANG_EFFECT.settingsShowForPlayersHint = i18n("ThandulsTogglableEffects.settingsShowForPlayers-hint"),

  LANG_EFFECT.conditionAlmostdead = i18n("ThandulsTogglableEffects.conditionAlmostdead"),
  LANG_EFFECT.conditionBlinded = i18n("ThandulsTogglableEffects.conditionBlinded"),
  LANG_EFFECT.conditionCharmed = i18n("ThandulsTogglableEffects.conditionCharmed"),
  LANG_EFFECT.conditionDead = i18n("ThandulsTogglableEffects.conditionDead"),
  LANG_EFFECT.conditionDeafened = i18n("ThandulsTogglableEffects.conditionDeafened"),
  LANG_EFFECT.conditionDiseased = i18n("ThandulsTogglableEffects.conditionDiseased"),
  LANG_EFFECT.conditionExhausted1 = i18n("ThandulsTogglableEffects.conditionExhausted1"),
  LANG_EFFECT.conditionExhausted2 = i18n("ThandulsTogglableEffects.conditionExhausted2"),
  LANG_EFFECT.conditionExhausted3 = i18n("ThandulsTogglableEffects.conditionExhausted3"),
  LANG_EFFECT.conditionExhausted4 = i18n("ThandulsTogglableEffects.conditionExhausted4"),
  LANG_EFFECT.conditionExhausted5 = i18n("ThandulsTogglableEffects.conditionExhausted5"),
  LANG_EFFECT.conditionFrightened = i18n("ThandulsTogglableEffects.conditionFrightened"),
  LANG_EFFECT.conditionGrappled = i18n("ThandulsTogglableEffects.conditionGrappled"),
  LANG_EFFECT.conditionIncapacitated = i18n("ThandulsTogglableEffects.conditionIncapacitated"),
  LANG_EFFECT.conditionInvisible = i18n("ThandulsTogglableEffects.conditionInvisible"),
  LANG_EFFECT.conditionParalyzed = i18n("ThandulsTogglableEffects.conditionParalyzed"),
  LANG_EFFECT.conditionPetrified = i18n("ThandulsTogglableEffects.conditionPetrified"),
  LANG_EFFECT.conditionPoisoned = i18n("ThandulsTogglableEffects.conditionPoisoned"),
  LANG_EFFECT.conditionProne = i18n("ThandulsTogglableEffects.conditionProne"),
  LANG_EFFECT.conditionRestrained = i18n("ThandulsTogglableEffects.conditionRestrained"),
  LANG_EFFECT.conditionStunned = i18n("ThandulsTogglableEffects.conditionStunned"),
  LANG_EFFECT.conditionUnconscious = i18n("ThandulsTogglableEffects.conditionUnconscious"),
  LANG_EFFECT.conditionWounded = i18n("ThandulsTogglableEffects.conditionWounded"),

  LANG_EFFECT.featureFavouredEnemy = i18n("ThandulsTogglableEffects.featureFavouredEnemy"),
  LANG_EFFECT.featureGreaterFavouredEnemy = i18n("ThandulsTogglableEffects.featureGreaterFavouredEnemy"),
  LANG_EFFECT.featureRage = i18n("ThandulsTogglableEffects.featureRage"),
  LANG_EFFECT.featureRagePathOfTheTotemWarrior = i18n("ThandulsTogglableEffects.featureRagePathOfTheTotemWarrior"),

  LANG_EFFECT.spellBane = i18n("ThandulsTogglableEffects.spellBane"),
  LANG_EFFECT.spellBarkskin = i18n("ThandulsTogglableEffects.spellBarkskin"),
  LANG_EFFECT.spellBless = i18n("ThandulsTogglableEffects.spellBless"),
  LANG_EFFECT.spellEnlarge = i18n("ThandulsTogglableEffects.spellEnlarge"),
  LANG_EFFECT.spellFly = i18n("ThandulsTogglableEffects.spellFly"),
  LANG_EFFECT.spellFortunesFavor = i18n("ThandulsTogglableEffects.spellFortunesFavor"),
  LANG_EFFECT.spellGiftOfAlacrity = i18n("ThandulsTogglableEffects.spellGiftOfAlacrity"),
  LANG_EFFECT.spellGuidance = i18n("ThandulsTogglableEffects.spellGuidance"),
  LANG_EFFECT.spellHaste = i18n("ThandulsTogglableEffects.spellHaste"),
  LANG_EFFECT.spellHuntersMark1h = i18n("ThandulsTogglableEffects.spellHuntersMark1h"),
  LANG_EFFECT.spellHuntersMark8h = i18n("ThandulsTogglableEffects.spellHuntersMark8h"),
  LANG_EFFECT.spellHuntersMark24h = i18n("ThandulsTogglableEffects.spellHuntersMark24h"),
  LANG_EFFECT.spellLongstrider = i18n("ThandulsTogglableEffects.spellLongstrider"),
  LANG_EFFECT.spellMageArmor = i18n("ThandulsTogglableEffects.spellMageArmor"),
  LANG_EFFECT.spellPassWithoutTrace = i18n("ThandulsTogglableEffects.spellPassWithoutTrace"),

  LANG_EFFECT.spellReduce = i18n("ThandulsTogglableEffects.spellReduce"),
  LANG_EFFECT.spellShield = i18n("ThandulsTogglableEffects.spellShield"),
  LANG_EFFECT.spellShieldOfFaith = i18n("ThandulsTogglableEffects.spellShieldOfFaith"),
  LANG_EFFECT.spellSlow = i18n("ThandulsTogglableEffects.spellSlow"),
  
  LANG_EFFECT.featureSharpshooter = i18n("ThandulsTogglableEffects.featureSharpshooter"),
  LANG_EFFECT.featureGreatWeaponMaster = i18n("ThandulsTogglableEffects.featureGreatWeaponMaster"),
//   LI-SETTING.title"  = i18n("ThandulsTogglableEffects."),
//   LI-SETTING.hint"   = i18n("ThandulsTogglableEffects."),
//   MD-SETTING.title"  = i18n("ThandulsTogglableEffects."),
//   MD-SETTING.hint"   = i18n("ThandulsTogglableEffects."),
//   TH-SETTING.title"  = i18n("ThandulsTogglableEffects."),
//   TH-SETTING.hint"   = i18n("ThandulsTogglableEffects."),
//   UE-SETTING.title"  : "i18n("ThandulsTogglableEffects."),
//   UE-SETTING.hint"   = i18n("ThandulsTogglableEffects."),
//   HS-SETTING.title"  = i18n("ThandulsTogglableEffects."),
//   HS-SETTING.hint"   = i18n("ThandulsTogglableEffects."),
//   ER-SETTING.title"  = i18n("ThandulsTogglableEffects."),
//   ER-SETTING.hint"   = i18n("ThandulsTogglableEffects."),

//   BlindingSettingTitle = i18n("ThandulsTogglableEffects."),
//   BlindingSettingHint = i18n("ThandulsTogglableEffects."),
//   BlindingSettingOption0 = i18n("ThandulsTogglableEffects."),
//   BlindingSettingOption1 = i18n("ThandulsTogglableEffects."),
//   BlindingSettingOption2 = i18n("ThandulsTogglableEffects."),
//   BlindingSettingOption3 = i18n("ThandulsTogglableEffects."),
//   condition-automationError = i18n("ThandulsTogglableEffects."),
//   BlindStatusTitle = i18n("ThandulsTogglableEffects."),
//   BlindStatusHint = i18n("ThandulsTogglableEffects."),
//   npcVisionTitle = i18n("ThandulsTogglableEffects."),
//   npcVisionHint = i18n("ThandulsTogglableEffects."),
//   shadowsTitle = i18n("ThandulsTogglableEffects."),
//   shadowsHint = i18n("ThandulsTogglableEffects."),
//   shadowsError = i18n("ThandulsTogglableEffects."),
//   shadowsSetting1 = i18n("ThandulsTogglableEffects."),
//   shadowsSetting2 = i18n("ThandulsTogglableEffects."),
//   shadowsSetting3 = i18n("ThandulsTogglableEffects."),

  LANG_EFFECT.visionDim0 = i18n("ThandulsTogglableEffects.visionDim0"),
  LANG_EFFECT.visionDim30 = i18n("ThandulsTogglableEffects.visionDim30"),
  LANG_EFFECT.visionDim60 = i18n("ThandulsTogglableEffects.visionDim60"),
  LANG_EFFECT.visionDim90 = i18n("ThandulsTogglableEffects.visionDim90"),
  LANG_EFFECT.visionDim120 = i18n("ThandulsTogglableEffects.visionDim120"),
  LANG_EFFECT.visionDim150 = i18n("ThandulsTogglableEffects.visionDim150"),
  LANG_EFFECT.visionDim180 = i18n("ThandulsTogglableEffects.visionDim180"),
  LANG_EFFECT.visionBright120 = i18n("ThandulsTogglableEffects.visionBright120"),

  LANG_EFFECT.lightNone = i18n("ThandulsTogglableEffects.lightNone"),
  LANG_EFFECT.lightCandle = i18n("ThandulsTogglableEffects.lightCandle"),
  LANG_EFFECT.lightLamp = i18n("ThandulsTogglableEffects.lightLamp"),
  LANG_EFFECT.lightBullseye = i18n("ThandulsTogglableEffects.lightBullseye"),
  LANG_EFFECT.lightHoodedDim = i18n("ThandulsTogglableEffects.lightHoodedDim"),
  LANG_EFFECT.lightHoodedBright = i18n("ThandulsTogglableEffects.lightHoodedBright"),
  LANG_EFFECT.lightLight = i18n("ThandulsTogglableEffects.lightLight"),
  LANG_EFFECT.lightTorch = i18n("ThandulsTogglableEffects.lightTorch"),
  LANG_EFFECT.lightMoonTouched = i18n("ThandulsTogglableEffects.lightMoonTouched")
}
